Switched chkbckshare from getopts to GNU getopt to allow long options. Implement long options.

diff --git a/src/scripts/chkbckshare.in b/src/scripts/chkbckshare.in
--- a/src/scripts/chkbckshare.in
+++ b/src/scripts/chkbckshare.in
@@ -17,7 +17,8 @@
 ## 	on								##
 ## 	/mnt/charybdisbck						##
 ##									##
-## Syntax:	chkbckshare [-b || -h || -t || -V]			##
+## Syntax:	chkbckshare [-b or --boolean || -h or --help ||		##
+##				-t or --terse || -V or --version]	##
 ##									##
 ## Exit Codes:	0 & 64 - 113 as per C/C++ standard			##
 ##		0 - success						##
@@ -38,6 +39,8 @@
 ##									##
 ## 21/12/2013	MG	1.1.1	First release.				##
 ## 22/11/2014	MG	1.1.2	Add overall package version to -V.	##
+## 22/11/2014	MG	1.1.3	Switched from getopts to GNU getopt to	##
+##				allow long options.			##
 ##									##
 ##########################################################################
 
@@ -50,9 +53,18 @@ outputprefix="chkbckshare: "
 mountoutput=""
 script_exit_code=0
 osname=$(uname -s)			# Get system name for OS differentiation
-version="1.1.2"				# set version variable
+version="1.1.3"				# set version variable
 etclocation=@sysconfdir@/backups	# Path to etc directory
 packageversion=@pkgversion@		# Version of the complete package
+
+# See getopt comments at the start of "Main"
+case $osname in
+*BSD)	binlocation=@bindir@"/"
+	;;
+# Linux)	Allow fall through for now as the defaults are linux.
+*)	binlocation=""
+	;;
+esac
 
 ###############
 ## Functions ##
@@ -66,6 +78,16 @@ output()
 		echo "$outputprefix$1"
 	else
 		echo "$outputprefix$1" 1>&2
+	fi
+}
+
+# Standard function to test command error ($1 is $?) and exit if non-zero
+std_cmd_err_handler()
+{
+	if [ $1 != 0 ]
+	then
+		script_exit_code=$1
+		script_exit
 	fi
 }
 
@@ -89,37 +111,66 @@ trap trap_exit SIGHUP SIGINT SIGTERM
 ##########
 ## Main ##
 ##########
-# Process command line arguments with getopts.
-while getopts :bhtV arg
+# Process command line arguments with GNU getopt.
+# (BSD includes, out of the box, a dodgy, feature lacking getopt program
+# installed in /usr/bin. A GNU compatable getopt package is available to install
+# and this gets installed in the bindir, ie /usr/local/bin. This means that the
+# dodgy getopt version is always found first on the PATH. In order to invoke the
+# correct program, $binlocation, (from Makefile bindir), is inserted in the command
+# line below to specify the full path). (Linux GNU getopt can be found on PATH so
+# binlocation ="").
+
+GETOPTTEMP=`"$binlocation"getopt -o bhtV --long boolean,help,terse,version -n "$0" -- "$@"`
+std_cmd_err_handler $?
+
+eval set -- "$GETOPTTEMP"
+std_cmd_err_handler $?
+
+while true
 do
-	case $arg in
-	b)	bool="TRUE"
+	case "$1" in
+	-b|--boolean)	bool="TRUE"
+		shift
 		;;
-	h)	echo "Usage is $0 [options]"
-		echo "	-b displays TRUE or FALSE instead of mount information"
+	-h|--help)	echo "Usage is $0 [options]"
+		echo "	-b or --boolean displays TRUE or FALSE instead of mount information"
 		echo "	OR"
-		echo "	-h displays usage information"
+		echo "	-h or --help displays usage information"
 		echo "	OR"
-		echo "	-t removes prepending script name from the output"
+		echo "	-t or --terse removes prepending script name from the output"
 		echo "	OR"
-		echo "	-V displays version information"
+		echo "	-V or --version displays version information"
+		shift
 		script_exit_code=0
 		script_exit
 		;;
-	t)	terse="TRUE"
+	-t|--terse)	terse="TRUE"
 		outputprefix=""
+		shift
 		;;
-	V)	echo "$0 Script version "$version
+	-V|--version)	echo "$0 Script version "$version
 		echo "$0 Package version "$packageversion
+		shift
 		script_exit_code=0
 		script_exit
 		;;
-	\?)	script_exit_code=64
-		output "Invalid argument -$OPTARG." 1
+	--)	shift
+		break
+		;;
+	*)	script_exit_code=1
+		output "Internal error." 1
 		script_exit
 		;;
 	esac
 done
+
+# Script does not accept other arguments.
+if [ $# -gt 0 ]
+then
+	script_exit_code=64
+	output "Invalid argument." 1
+	script_exit
+fi
 
 # Read parameters from $etclocation/backups.conf
 IFS="="
