Switched detbckshare from getopts to GNU getopt to allow long options. Implement long options.

diff --git a/src/scripts/detbckshare.in b/src/scripts/detbckshare.in
--- a/src/scripts/detbckshare.in
+++ b/src/scripts/detbckshare.in
@@ -17,7 +17,7 @@
 ##	from								##
 ## 	\\MyServer\mybackupdirectory					##
 ##									##
-## Syntax:	detbckshare [-h || -v || -V ]				##
+## Syntax:	detbckshare [-h --help || -v --verbose || -V --version ]##
 ##									##
 ## Exit Codes:	0 & 64 - 113 as per C/C++ standard			##
 ##		0 - success						##
@@ -72,6 +72,8 @@
 ##				version option to -V. Added verbose	##
 ##				option -v.				##
 ## 22/11/2014	MG	1.1.2	Add overall package version to -V.	##
+## 22/11/2014	MG	1.1.3	Switched from getopts to GNU getopt to	##
+##				allow long options.			##
 ##									##
 ##########################################################################
 
@@ -80,10 +82,20 @@
 ####################
 script_exit_code=0
 outputprefix="detbckshare: "
-version="1.1.2"				# set version variable
+osname=$(uname -s)			# Get system name for OS differentiation
+version="1.1.3"				# set version variable
 etclocation=@sysconfdir@/backups	# Path to etc directory
 verbosity=""
 packageversion=@pkgversion@		# Version of the complete package
+
+# See getopt comments at the start of "Main"
+case $osname in
+*BSD)	binlocation=@bindir@"/"
+	;;
+# Linux)	Allow fall through for now as the defaults are linux.
+*)	binlocation=""
+	;;
+esac
 
 ###############
 ## Functions ##
@@ -100,6 +112,16 @@ output()
 		fi
 	else
 		echo "$outputprefix$1" 1>&2
+	fi
+}
+
+# Standard function to test command error ($1 is $?) and exit if non-zero
+std_cmd_err_handler()
+{
+	if [ $1 != 0 ]
+	then
+		script_exit_code=$1
+		script_exit
 	fi
 }
 
@@ -123,32 +145,60 @@ trap trap_exit SIGHUP SIGINT SIGTERM
 ##########
 ## Main ##
 ##########
-# Process command line arguments with getopts.
-while getopts :hvV arg
+# Process command line arguments with GNU getopt.
+# (BSD includes, out of the box, a dodgy, feature lacking getopt program
+# installed in /usr/bin. A GNU compatable getopt package is available to install
+# and this gets installed in the bindir, ie /usr/local/bin. This means that the
+# dodgy getopt version is always found first on the PATH. In order to invoke the
+# correct program, $binlocation, (from Makefile bindir), is inserted in the command
+# line below to specify the full path). (Linux GNU getopt can be found on PATH so
+# binlocation ="").
+
+GETOPTTEMP=`"$binlocation"getopt -o hvV --long help,verbose,version -n "$0" -- "$@"`
+std_cmd_err_handler $?
+
+eval set -- "$GETOPTTEMP"
+std_cmd_err_handler $?
+
+while true
 do
-	case $arg in
-	h)	echo "Usage is $0 [options]"
-		echo "	-h displays usage information"
+	case "$1" in
+	-h|--help)	echo "Usage is $0 [options]"
+		echo "	-h or --help displays usage information"
 		echo "	OR"
-		echo "	-v verbose output"
+		echo "	-v or --verbose verbose output"
 		echo "	OR"
-		echo "	-V displays version information"
+		echo "	-V or --version displays version information"
+		shift
 		script_exit_code=0
 		script_exit
 		;;
-	v)	verbosity="-v"
+	-v|--verbose)	verbosity="-v"
+		shift
 		;;
-	V)	echo "$0 Script version "$version
+	-V|--version)	echo "$0 Script version "$version
 		echo "$0 Package version "$packageversion
+		shift
 		script_exit_code=0
 		script_exit
 		;;
-	\?)	script_exit_code=64
-		output "Invalid argument -$OPTARG." 1
+	--)	shift
+		break
+		;;
+	*)	script_exit_code=1
+		output "Internal error." 1
 		script_exit
 		;;
 	esac
 done
+
+# Script does not accept other arguments.
+if [ $# -gt 0 ]
+then
+	script_exit_code=64
+	output "Invalid argument." 1
+	script_exit
+fi
 
 # Read parameters from $etclocation/backups.conf
 IFS="="
