attbckshare.sh.in: Remove script_exit_code
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/attbckshare.sh.in b/src/prg/bash/attbckshare.sh.in
--- a/src/prg/bash/attbckshare.sh.in
+++ b/src/prg/bash/attbckshare.sh.in
@@ -105,16 +105,16 @@
 # 09/01/2019	MG	1.2.8	Use absolute bash path in shebang	#
 #				instead of env. Using env is OK for a 	#
 #				non-AutoTools script.			#
-# 17/01/2019	MG	1.2.9	Do not hard code outputprefix contents.	#
+# 18/01/2019	MG	1.2.9	Do not hard code outputprefix contents.	#
 #				Make true booleans.			#
 #				Standardise parameters of output().	#
+#				Remove script_exit_code variable.	#
 #									#
 #########################################################################
 
 ##################
 # Init variables #
 ##################
-script_exit_code=0
 outputprefix="$(basename $0):"
 version=1.2.9				# set version variable
 etclocation=@sysconfdir@/lixbackups	# Path to etc directory
@@ -165,27 +165,34 @@ output()
 std_cmd_err_handler()
 {
 	if [ $1 != 0 ]; then
-		script_exit_code=$1
-		script_exit
+		script_exit $1
 	fi
 }
 
-# Standard function to tidy up and return exit code
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
 script_exit()
 {
-	exit $script_exit_code
+	exit $1
 }
 
-# Standard trap exit function
+# Standard trap exit function.
+# No parameters.
+# No return value.
 trap_exit()
 {
-script_exit_code=1
-output "Script terminating due to trap received. Code: "$script_exit_code 1 1
-script_exit
+	local exit_code=$?
+	local msg
+
+	msg="Script terminating with exit code $exit_code due to trap received."
+	output "$msg" 1 0
+	script_exit $exit_code
 }
 
-# Setup trap
-trap trap_exit SIGHUP SIGINT SIGTERM
+# Setup trap.
+trap trap_exit SIGHUP SIGINT SIGQUIT SIGTERM
+
 
 ########
 # Main #
@@ -202,9 +209,8 @@ while true; do
 	case "$1" in
 	-a|--adhoc)
 		if $weekly ; then
-			script_exit_code=1
 			output "Options a and w are mutually exclusive." 1 0
-			script_exit
+			script_exit 1
 		fi
 		adhoc=true
 		bckuptype="adhoc"
@@ -222,8 +228,7 @@ while true; do
 		echo "	OR"
 		echo "	-w or --weekly mount the weekly target backup share"
 		shift
-		script_exit_code=0
-		script_exit
+		script_exit 0
 		;;
 	-v|--verbose)
 		verbosity="-v"
@@ -233,14 +238,12 @@ while true; do
 		echo "$0 Script version "$version
 		echo "$0 Package version "$packageversion
 		shift
-		script_exit_code=0
-		script_exit
+		script_exit 0
 		;;
 	-w|--weekly)
 		if $adhoc ; then
-			script_exit_code=1
 			output "Options a and w are mutually exclusive." 1 0
-			script_exit
+			script_exit 1
 		fi
 		weekly=true
 		bckuptype="weekly"
@@ -249,25 +252,22 @@ while true; do
 	--)	shift
 		break
 		;;
-	*)	script_exit_code=1
-		output "Internal error." 1 0
-		script_exit
+	*)	output "Internal error." 1 0
+		script_exit 1
 		;;
 	esac
 done
 
 # Script does not accept other arguments.
 if [ $# -gt 0 ]; then
-	script_exit_code=1
 	output "Invalid argument." 1 0
-	script_exit
+	script_exit 1
 fi
 
 # One option has to be selected.
 if ! $adhoc && ! $weekly ; then
-	script_exit_code=1
 	output "Either a or w must be set." 1 0
-	script_exit
+	script_exit 1
 fi
 
 # Read parameters from $etclocation/backups.conf
@@ -337,9 +337,8 @@ CIFS)
 		mountCL+=" -o vers=$cifsversion"
 	fi
 	;;
-*)	script_exit_code=1
-	output "Invalid share type." 1 1
-	script_exit
+*)	output "Invalid share type." 1 1
+	script_exit 1
 	;;
 esac
 
@@ -348,20 +347,17 @@ if [ "$(chkbckshare -bt)" = "FALSE" ]; then
 	eval "$mountCL"
 	status=$?
 	if [ $status != 0 ]; then
-		script_exit_code=1
-		msg="Failed to mount backup share. Mount error: "$status
-		msg+=" Script exit code: "$script_exit_code
+		msg="Failed to mount backup share. Mount error: $status"
+		msg+=" Script exit code: $status"
 		output $msg 1 1
-		script_exit
+		script_exit $status
 	fi
 else
-	script_exit_code=1
-	msg="Backup share already mounted. Script exit code: "
-	msg+=$script_exit_code
+	msg="Backup share already mounted."
 	output $msg 1 1
-	script_exit
+	script_exit 1
 fi
 
-script_exit_code=0
 output "Share $target mounted on $mntdir" 0 1
-script_exit
+script_exit 0
+
