attbckshare: Refactor CL processing into function
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/attbckshare.sh.in b/src/prg/bash/attbckshare.sh.in
--- a/src/prg/bash/attbckshare.sh.in
+++ b/src/prg/bash/attbckshare.sh.in
@@ -111,6 +111,7 @@
 #				Remove script_exit_code variable.	#
 #				Improve if statements with [[ ... ]].	#
 #				Change verbosity to verbose boolean.	#
+#				Refactor into functions.		#
 #									#
 #########################################################################
 
@@ -214,73 +215,88 @@ trap_exit()
 # Setup trap.
 trap trap_exit SIGHUP SIGINT SIGQUIT SIGTERM
 
+# Process command line arguments with GNU getopt.
+# Parameters -	$1 is the command line.
+# No return value.
+proc_CL()
+{
+	local GETOPTTEMP
+	local msg
+	local tmpGETOPTTEMP
+
+	tmpGETOPTTEMP="getopt -o ahvVw --long adhoc,help,verbose,version,"
+	tmpGETOPTTEMP+="weekly"
+	GETOPTTEMP=`$tmpGETOPTTEMP -n "$0" -- "$@"`
+	std_cmd_err_handler $?
+
+	eval set -- "$GETOPTTEMP"
+	std_cmd_err_handler $?
+
+	while true; do
+		case "$1" in
+		-a|--adhoc)
+			if $weekly ; then
+				msg="Options a and w are mutually exclusive."
+				output "$msg" 1 0
+				script_exit 1
+			fi
+			adhoc=true
+			bckuptype="adhoc"
+			shift
+			;;
+		-h|--help)
+			usage
+			shift
+			script_exit 0
+			;;
+		-v|--verbose)
+			verbose=true
+			shift
+			;;
+		-V|--version)
+			echo "$0 Script version "$version
+			echo "$0 Package version "$packageversion
+			shift
+			script_exit 0
+			;;
+		-w|--weekly)
+			if $adhoc ; then
+				msg="Options a and w are mutually exclusive."
+				output "$msg" 1 0
+				script_exit 1
+			fi
+			weekly=true
+			bckuptype="weekly"
+			shift
+			;;
+		--)	shift
+			break
+			;;
+		*)	output "Internal error." 1 0
+			script_exit 1
+			;;
+		esac
+	done
+
+	# Script does not accept other arguments.
+	if [[ $# > 0 ]]; then
+		output "Invalid argument." 1 0
+		script_exit 1
+	fi
+
+	# One option has to be selected.
+	if ! $adhoc && ! $weekly ; then
+		output "Either a or w must be set." 1 0
+		script_exit 1
+	fi
+}
+
 
 ########
 # Main #
 ########
-# Process command line arguments with GNU getopt.
-GETOPTTEMP=`getopt -o ahvVw --long adhoc,help,verbose,version,weekly \
-	-n "$0" -- "$@"`
-std_cmd_err_handler $?
 
-eval set -- "$GETOPTTEMP"
-std_cmd_err_handler $?
-
-while true; do
-	case "$1" in
-	-a|--adhoc)
-		if $weekly ; then
-			output "Options a and w are mutually exclusive." 1 0
-			script_exit 1
-		fi
-		adhoc=true
-		bckuptype="adhoc"
-		shift
-		;;
-	-h|--help)
-		usage
-		shift
-		script_exit 0
-		;;
-	-v|--verbose)
-		verbose=true
-		shift
-		;;
-	-V|--version)
-		echo "$0 Script version "$version
-		echo "$0 Package version "$packageversion
-		shift
-		script_exit 0
-		;;
-	-w|--weekly)
-		if $adhoc ; then
-			output "Options a and w are mutually exclusive." 1 0
-			script_exit 1
-		fi
-		weekly=true
-		bckuptype="weekly"
-		shift
-		;;
-	--)	shift
-		break
-		;;
-	*)	output "Internal error." 1 0
-		script_exit 1
-		;;
-	esac
-done
-
-# Script does not accept other arguments.
-if [[ $# > 0 ]]; then
-	output "Invalid argument." 1 0
-	script_exit 1
-fi
-
-# One option has to be selected.
-if ! $adhoc && ! $weekly ; then
-	output "Either a or w must be set." 1 0
-	script_exit 1
-fi
+proc_CL "$@"
 
 # Read parameters from $etclocation/backups.conf
 IFS="="
