chkbckshare: Remove script_exit_code_variable
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/chkbckshare.sh.in b/src/prg/bash/chkbckshare.sh.in
--- a/src/prg/bash/chkbckshare.sh.in
+++ b/src/prg/bash/chkbckshare.sh.in
@@ -60,6 +60,7 @@
 # 20/01/2019	MG	1.2.7	Do not hard code outputprefix contents.	#
 #				Use true booleans.			#
 #				Standardise output function.		#
+#				Remove script_exit_code variable.	#
 #									#
 #########################################################################
 
@@ -68,7 +69,6 @@
 ##################
 outputprefix="$(basename $0):"
 mountoutput=""
-script_exit_code=0
 version=1.2.7				# set version variable
 etclocation=@sysconfdir@/lixbackups	# Path to etc directory
 packageversion=@pkgversion@		# Version of the complete package
@@ -95,27 +95,29 @@ output()
 	fi
 }
 
-# Standard function to test command error ($1 is $?) and exit if non-zero
+# Standard function to test command error and exit if non-zero.
+# Parameters - $1 is $?
+# No return value.
 std_cmd_err_handler()
 {
 	if [ $1 != 0 ]; then
-		script_exit_code=$1
-		script_exit
+		script_exit $1
 	fi
 }
 
-# Standard function to tidy up and return exit code
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
 script_exit()
 {
-	exit $script_exit_code
+	exit $1
 }
 
 # Standard trap exit function
 trap_exit()
 {
-script_exit_code=1
-output "Script terminating due to trap received. Code: "$script_exit_code 1
-script_exit
+output "Script terminating due to trap received. Code: 1" 1
+script_exit 1
 }
 
 # Setup trap
@@ -151,8 +153,7 @@ while true; do
 		echo "	OR"
 		echo "	-V or --version displays version information"
 		shift
-		script_exit_code=0
-		script_exit
+		script_exit 0
 		;;
 	-t|--terse)
 		terse=true
@@ -163,24 +164,21 @@ while true; do
 		echo "$0 Script version "$version
 		echo "$0 Package version "$packageversion
 		shift
-		script_exit_code=0
-		script_exit
+		script_exit 0
 		;;
 	--)	shift
 		break
 		;;
-	*)	script_exit_code=1
-		output "Internal error." 1
-		script_exit
+	*)	output "Internal error." 1
+		script_exit 1
 		;;
 	esac
 done
 
 # Script does not accept other arguments.
 if [ $# -gt 0 ]; then
-	script_exit_code=1
 	output "Invalid argument." 1
-	script_exit
+	script_exit 1
 fi
 
 # Read parameters from $etclocation/backups.conf
@@ -212,5 +210,5 @@ else
 	fi
 fi
 
-script_exit_code=0
-script_exit
+script_exit 0
+
