bash: Move script_exit() before it is used
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/chkbckshare.sh.in b/src/prg/bash/chkbckshare.sh.in
--- a/src/prg/bash/chkbckshare.sh.in
+++ b/src/prg/bash/chkbckshare.sh.in
@@ -94,6 +94,7 @@
 #				Specify type for numeric variables.	#
 # 19/04/2019	MG	1.3.2	Replace obsolete backticks with $(cmd).	#
 # 09/08/2019	MG	1.3.3	Correct getopt CL for proper quoting.	#
+# 11/10/2019	MG	1.3.4	Move script_exit() before it is used.	#
 #									#
 #########################################################################
 
@@ -101,7 +102,7 @@
 # Init variables #
 ##################
 outputprefix="$(basename $0): "			# Can be altered by --terse CLA
-readonly version=1.3.3				# set version variable
+readonly version=1.3.4				# set version variable
 readonly packageversion=@pkgversion@		# Version of the package
 readonly etclocation=@sysconfdir@/lixbackups	# Path to etc directory
 
@@ -145,6 +146,14 @@ output()
 	fi
 }
 
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
+script_exit()
+{
+	exit $1
+}
+
 # Standard function to test command error and exit if non-zero.
 # Parameters - $1 is $?
 # No return value.
@@ -153,14 +162,6 @@ std_cmd_err_handler()
 	if (( $1 )); then
 		script_exit $1
 	fi
-}
-
-# Standard function to tidy up and return exit code.
-# Parameters - 	$1 is the exit code.
-# No return value.
-script_exit()
-{
-	exit $1
 }
 
 # Standard trap exit function.
diff --git a/src/prg/bash/netbckup.sh.in b/src/prg/bash/netbckup.sh.in
--- a/src/prg/bash/netbckup.sh.in
+++ b/src/prg/bash/netbckup.sh.in
@@ -148,6 +148,7 @@
 # 09/08/2019	MG	1.3.4	Correct getopt CL for proper quoting.	#
 # 11/10/2019	MG	1.3.5	Move std_cmd_err_handler() before it is	#
 #				used.					#
+#				Move script_exit() before it is used.	#
 #									#
 #########################################################################
 
@@ -190,38 +191,6 @@ Usage is $0 [options]
 EOF
 }
 
-# Standard function to test command error and exit if non-zero.
-# Parameters - $1 is $?
-# No return value.
-std_cmd_err_handler()
-{
-	if (( $1 )); then
-		script_exit $1
-	fi
-}
-
-# Standard function to emit messages depending on various parameters.
-# Parameters -	$1 What:-	The message to emit.
-#		$2 Where:-	stdout == 0
-#				stderr != 0
-#		$3 Syslog:-	$3 == 0, No.
-#				$3 != 0, Yes.
-# No return value.
-output()
-{
-	if (( !$2 )); then
-		printf "%s %s %s\n" "$(date +'[ %a %b %d %T ]')" $outputprefix \
-			"$1"
-	else
-		printf "%s %s %s\n" "$(date +'[ %a %b %d %T ]')" $outputprefix \
-			"$1" 1>&2
-	fi
-	if (( $3 )); then
-		logger "$outputprefix $1"
-		std_cmd_err_handler $?
-	fi
-}
-
 # Standard function to tidy up and return exit code.
 # Parameters - 	$1 is the exit code.
 # No return value.
@@ -254,6 +223,38 @@ script_exit()
 	output "$script_short_desc completed with status $1" $1 0
 
 	exit $1
+}
+
+# Standard function to test command error and exit if non-zero.
+# Parameters - $1 is $?
+# No return value.
+std_cmd_err_handler()
+{
+	if (( $1 )); then
+		script_exit $1
+	fi
+}
+
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr != 0
+#		$3 Syslog:-	$3 == 0, No.
+#				$3 != 0, Yes.
+# No return value.
+output()
+{
+	if (( !$2 )); then
+		printf "%s %s %s\n" "$(date +'[ %a %b %d %T ]')" $outputprefix \
+			"$1"
+	else
+		printf "%s %s %s\n" "$(date +'[ %a %b %d %T ]')" $outputprefix \
+			"$1" 1>&2
+	fi
+	if (( $3 )); then
+		logger "$outputprefix $1"
+		std_cmd_err_handler $?
+	fi
 }
 
 # Standard trap exit function.
