bash: Move std_cmd_err_handler() before it is used
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/netbckup.sh.in b/src/prg/bash/netbckup.sh.in
--- a/src/prg/bash/netbckup.sh.in
+++ b/src/prg/bash/netbckup.sh.in
@@ -146,6 +146,8 @@
 # 18/03/2019	MG	1.3.2	Fix globbing of trashbox emptying.	#
 # 19/04/2019	MG	1.3.3	Replace obsolete backticks with $(cmd).	#
 # 09/08/2019	MG	1.3.4	Correct getopt CL for proper quoting.	#
+# 11/10/2019	MG	1.3.5	Move std_cmd_err_handler() before it is	#
+#				used.					#
 #									#
 #########################################################################
 
@@ -154,7 +156,7 @@
 ##################
 readonly outputprefix="$(basename $0):"
 
-readonly version=1.3.4				# Script version
+readonly version=1.3.5				# Script version
 readonly packageversion=@pkgversion@		# Package version
 
 readonly etclocation=@sysconfdir@/lixbackups	# Path to config directory
@@ -188,6 +190,16 @@ Usage is $0 [options]
 EOF
 }
 
+# Standard function to test command error and exit if non-zero.
+# Parameters - $1 is $?
+# No return value.
+std_cmd_err_handler()
+{
+	if (( $1 )); then
+		script_exit $1
+	fi
+}
+
 # Standard function to emit messages depending on various parameters.
 # Parameters -	$1 What:-	The message to emit.
 #		$2 Where:-	stdout == 0
@@ -207,16 +219,6 @@ output()
 	if (( $3 )); then
 		logger "$outputprefix $1"
 		std_cmd_err_handler $?
-	fi
-}
-
-# Standard function to test command error and exit if non-zero.
-# Parameters - $1 is $?
-# No return value.
-std_cmd_err_handler()
-{
-	if (( $1 )); then
-		script_exit $1
 	fi
 }
 
