netbckup: Standardise script_exit and exit codes
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/netbckup.sh.in b/src/prg/bash/netbckup.sh.in
--- a/src/prg/bash/netbckup.sh.in
+++ b/src/prg/bash/netbckup.sh.in
@@ -31,8 +31,31 @@
 #			-s or --selective || -V or --version ||		#
 #			-w or --weekly ]				#
 #									#
-# Exit Codes:	0 - success						#
-#		1 - failure						#
+# Exit codes used:-							#
+# Bash standard Exit Codes:	0 - success				#
+#				1 - general failure			#
+# User-defined exit code range is 64 - 113				#
+#	C/C++ Semi-standard exit codes from sysexits.h range is 64 - 78	#
+#		EX_USAGE	64	command line usage error	#
+#		EX_DATAERR	65	data format error		#
+#		EX_NOINPUT	66	cannot open input		#
+#		EX_NOUSER	67	addressee unknown		#
+#		EX_NOHOST	68	host name unknown		#
+#		EX_UNAVAILABLE	69	service unavailable		#
+#		EX_SOFTWARE	70	internal software error		#
+#		EX_OSERR	71	system error (e.g., can't fork)	#
+#		EX_OSFILE	72	critical OS file missing	#
+#		EX_CANTCREAT	73	can't create (user) output file	#
+#		EX_IOERR	74	input/output error		#
+#		EX_TEMPFAIL	75	temp failure; user is invited	#
+#					to retry			#
+#		EX_PROTOCOL	76	remote error in protocol	#
+#		EX_NOPERM	77	permission denied		#
+#		EX_CONFIG	78	configuration error		#
+#	User-defined (here) exit codes range 79 - 113:			#
+#		None							#
+#									#
+# Further Info:								#
 #									#
 #########################################################################
 
@@ -98,16 +121,16 @@
 # 09/01/2019	MG	1.2.13	Use absolute bash path in shebang	#
 #				instead of env. Using env is OK for a 	#
 #				non-AutoTools script.			#
-# 21/01/2019	MG	1.3.1	Do not hard code outputprefix contents.	#
+# 22/01/2019	MG	1.3.1	Do not hard code outputprefix contents.	#
 #				Use true booleans.			#
 #				Standardise output function.		#
+#				Standardise script_exit and exit codes.	#
 #									#
 #########################################################################
 
 ##################
 # Init variables #
 ##################
-script_exit_code=0
 version=1.3.1				# set version variable
 etclocation=@sysconfdir@/lixbackups	# Path to etc directory
 outputprefix="$(basename $0):"
@@ -151,56 +174,53 @@ output()
 	fi
 }
 
-# Standard function to test command error ($1 is $?) and exit if non-zero
+# Standard function to test command error and exit if non-zero.
+# Parameters - $1 is $?
+# No return value.
 std_cmd_err_handler()
 {
 	if [ $1 != 0 ]; then
-		script_exit_code=$1
-		script_exit
+		script_exit $1
 	fi
 }
 
-# Standard function to cleanup and return exit code
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
 script_exit()
 {
-# The backup share might or might not be mounted.
-if [ "$(chkbckshare -bt)" = "TRUE" ]; then
-	detbckshare
-	# No error check cos could loop via std_cmd_err_handler
-fi
+	# The backup share might or might not be mounted.
+	if [ "$(chkbckshare -bt)" = "TRUE" ]; then
+		detbckshare
+		# No error check cos could loop via std_cmd_err_handler
+	fi
 
-# FD's 6 & 7 may or may not be open at this point so test individually for
-# closing. This reads lsof with ANDed conditions of suppress warnings, FD 6,
-# output only FD for this current PID and pipe it's output to wc to count the
-# lines. If FD 6 is open, 2 lines result, PID number and f6.
-if [ $(lsof -aw -d 6 -F f -p $$ | wc -l) -gt 0 ]; then
-	# Final log entries and restore stdout & stderr
-	output "$script_short_desc completed with status $script_exit_code" \
-		$script_exit_code FALSE
-	msg="Processing of $backpath is complete. Status: $script_exit_code"
-	output "$msg" $script_exit_code 0
+	# FD's 6 & 7 may or may not be open at this point so test individually
+	# for closing. This reads lsof with ANDed conditions of; suppress
+	# warnings, FD 6, output only FD for this current PID and pipe it's
+	# output to wc to count the lines. If FD 6 is open, 2 lines result, PID
+	# number and f6.
+	if [[ $(lsof -aw -d 6 -F f -p $$ | wc -l) > 0 ]]; then
+		output "$script_short_desc completed with status $1" $1 1
+		exec 1>&6 6>&-	# Restore stdout and close FD 6
+	fi
+	if [[ $(lsof -aw -d 7 -F f -p $$ | wc -l) > 0 ]]; then
+		exec 2>&7 7>&-	# Restore stderr and close FD 7
+	fi
 
-	exec 1>&6 6>&-	# Restore stdout and close FD 6
-fi
-if [ $(lsof -aw -d 7 -F f -p $$ | wc -l) -gt 0 ]; then
-	exec 2>&7 7>&-	# Restore stderr and close FD 7
-fi
+	# Re-Allow logins
+	rm -f /etc/nologin
 
-# Re-Allow logins
-rm -f /etc/nologin
+	output "$script_short_desc completed with status $1" $1 0
 
-output "$script_short_desc completed with status $script_exit_code" \
-	$script_exit_code 1
-
-exit $script_exit_code
+	exit $1
 }
 
 # Standard trap exit function
 trap_exit()
 {
-script_exit_code=1
 output "Script terminating due to trap received." 1 1
-script_exit
+script_exit 1
 }
 
 # Setup trap
@@ -213,16 +233,10 @@ trap trap_exit SIGHUP SIGINT SIGTERM
 GETOPTTEMP=`getopt -o dfhisVw \
 	--long differential,full,help,incremental,selective,version,weekly \
 	-n "$0" -- "$@"`
-status=$?
-if [ $status != 0 ]; then
-	exit $status
-fi
+std_cmd_err_handler $?
 
 eval set -- "$GETOPTTEMP"
-status=$?
-if [ $status != 0 ]; then
-	exit $status
-fi
+std_cmd_err_handler $?
 
 while true; do
 	case "$1" in
@@ -230,8 +244,8 @@ while true; do
 		if $fulladhoc || $incremental || $selective || $weekly; then
 			msg="Options d, f, i, s and w are all mutually "
 			msg+="exclusive."
-			output "$msg" 64 0
-			exit 64
+			output "$msg" 1 0
+			script_exit 64
 		fi
 		differential=true
 		bckuptype="differential"
@@ -244,8 +258,8 @@ while true; do
 		if $differential || $incremental || $selective || $weekly; then
 			msg="Options d, f, i, s and w are all mutually "
 			msg+="exclusive."
-			output "$msg" 64 0
-			exit 64
+			output "$msg" 1 0
+			script_exit 64
 		fi
 		fulladhoc=true
 		bckuptype="fulladhoc"
@@ -265,14 +279,14 @@ while true; do
 		echo "	OR"
 		echo "	-w or --weekly - perform a weekly full backup"
 		shift
-		exit 0
+		script_exit 0
 		;;
 	-i|--incremental)
 		if $fulladhoc || $differential || $selective || $weekly; then
 			msg="Options d, f, i, s and w are all mutually "
 			msg+="exclusive."
-			output "$msg" 64 0
-			exit 64
+			output "$msg" 1 0
+			script_exit 64
 		fi
 		incremental=true
 		bckuptype="incremental"
@@ -285,8 +299,8 @@ while true; do
 		if $fulladhoc || $differential || $incremental || $weekly; then
 			msg="Options d, f, i, s and w are all mutually "
 			msg+="exclusive."
-			output "$msg" 64 0
-			exit 64
+			output "$msg" 1 0
+			script_exit 64
 		fi
 		selective=true
 		bckuptype="selective"
@@ -297,15 +311,15 @@ while true; do
 	-V|--version)	echo "$0 Script version "$version
 		echo "$0 Package version "$packageversion
 		shift
-		exit 0
+		script_exit 0
 		;;
 	-w|--weekly)
 		if $fulladhoc || $differential || $incremental \
 			|| $selective; then
 			msg="Options d, f, i, s and w are all mutually "
 			msg+="exclusive."
-			output "$msg" 64 0
-			exit 64
+			output "$msg" 1 0
+			script_exit 64
 		fi
 		weekly=true
 		bckuptype="weekly"
@@ -331,22 +345,22 @@ while true; do
 		break
 		;;
 	*)	output "Internal error." 1 0
-		exit 1
+		script_exit 64
 		;;
 	esac
 done
 
 # Script does not accept other arguments.
 if [ $# -gt 0 ]; then
-	output "Invalid argument." 64 0
-	exit 64
+	output "Invalid argument." 1 0
+	script_exit 64
 fi
 
 # One option has to be selected.
 if ! $differential && ! $fulladhoc && ! $incremental && ! $selective \
 	&& ! $weekly; then
-	output "Either d, f, i, s or w must be set." 64 0
-	exit 64
+	output "Either d, f, i, s or w must be set." 1 0
+	script_exit 64
 fi
 
 output "Refer to $loglocation/lixbackups.log for further information." 0 1
@@ -444,11 +458,11 @@ differential)
 		cp $mntdir/backup.snar $snarpath
 		std_cmd_err_handler $?
 	else
-		script_exit_code=1
+		status=66
 		msg="backup.snar does not exist or is not accessible. Exit "
-		msg+="code $script_exit_code"
+		msg+="code $status"
 		output "$msg" 1 1
-		script_exit
+		script_exit $status
 	fi
 
 	bckupCL+="$backpath --exclude-from=$etclocation/bckdaily.exclude "
@@ -475,11 +489,11 @@ incremental)
 
 	# Check that the incremental file exists.
 	if [ ! -f $snarpath -o ! -r $snarpath -o ! -w $snarpath ]; then
-		script_exit_code=1
+		status=66
 		msg="$snarpath does not exist or is not accessible. Exit "
-		msg+="code $script_exit_code"
+		msg+="code $status"
 		output "$msg" 1 1
-		script_exit
+		script_exit $status
 	fi
 
 	bckupCL+="$backpath --exclude-from=$etclocation/bckdaily.exclude "
@@ -577,6 +591,8 @@ df -h | mailx -s "$script_short_desc" $notifyuser
 # Mail backup file date hierarchy
 ls -lht $mntdir | mailx -s "$script_short_desc" $notifyuser
 
+output "Processing of $backpath is complete. Status: 0" 0 1
+
 # And exit.
-script_exit_code=0
-script_exit
+script_exit 0
+
