netbckup: Clone ownership and perms for logfile
Copy the ownership and permissions from syslog or messages if available
or use defaults.

Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/netbckup.sh.in b/src/prg/bash/netbckup.sh.in
--- a/src/prg/bash/netbckup.sh.in
+++ b/src/prg/bash/netbckup.sh.in
@@ -121,7 +121,7 @@
 # 09/01/2019	MG	1.2.13	Use absolute bash path in shebang	#
 #				instead of env. Using env is OK for a 	#
 #				non-AutoTools script.			#
-# 25/01/2019	MG	1.3.1	Do not hard code outputprefix contents.	#
+# 27/01/2019	MG	1.3.1	Do not hard code outputprefix contents.	#
 #				Use true booleans.			#
 #				Standardise output function.		#
 #				Standardise script_exit and exit codes.	#
@@ -132,6 +132,9 @@
 #				Replace last sed with awk.		#
 #				Reinforce find function.		#
 #				Localise variables where appropriate.	#
+#				Create logfile with ownership and	#
+#				permissions based on either syslog,	#
+#				messages or default.			#
 #									#
 #########################################################################
 
@@ -397,6 +400,29 @@ proc_CL()
 	fi
 }
 
+# Create the logfile with ownership and permissions copied from syslog or
+# messages, if available, or just defaulting if not.
+# Parameters - none.
+# No return value.
+cre_logfile()
+{
+	local logname
+
+	if [[ -f $loglocation/syslog ]]; then
+		logname=$loglocation/syslog
+	elif [[ -f $loglocation/messages ]]; then
+		logname=$loglocation/messages
+	fi
+	touch $loglocation/lixbackups.log
+	std_cmd_err_handler $?
+	if [[ $logname ]]; then
+		chown --reference=$logname  $loglocation/lixbackups.log
+		std_cmd_err_handler $?
+		chmod --reference=$logname  $loglocation/lixbackups.log
+		std_cmd_err_handler $?
+	fi
+}
+
 # Ensure logfile exists and is accessible.
 # Parameters - None.
 # No return value.
@@ -408,12 +434,7 @@ chk_logfile()
 	std_cmd_err_handler $?
 
 	if [[ ! -e $loglocation/lixbackups.log ]]; then
-		touch "$loglocation/lixbackups.log"
-		std_cmd_err_handler $?
-		chown root:adm "$loglocation/lixbackups.log"
-		std_cmd_err_handler $?
-		chmod 0640 "$loglocation/lixbackups.log"
-		std_cmd_err_handler $?
+		cre_logfile
 	elif [[ ! -f $loglocation/lixbackups.log \
 		|| ! -r $loglocation/lixbackups.log \
 		|| ! -w $loglocation/lixbackups.log ]]; then
