netbckup: Refactor build backup CL into function
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/netbckup.sh.in b/src/prg/bash/netbckup.sh.in
--- a/src/prg/bash/netbckup.sh.in
+++ b/src/prg/bash/netbckup.sh.in
@@ -121,7 +121,7 @@
 # 09/01/2019	MG	1.2.13	Use absolute bash path in shebang	#
 #				instead of env. Using env is OK for a 	#
 #				non-AutoTools script.			#
-# 24/01/2019	MG	1.3.1	Do not hard code outputprefix contents.	#
+# 25/01/2019	MG	1.3.1	Do not hard code outputprefix contents.	#
 #				Use true booleans.			#
 #				Standardise output function.		#
 #				Standardise script_exit and exit codes.	#
@@ -587,6 +587,119 @@ prod_adhoc_excl_list()
 	std_cmd_err_handler $?
 }
 
+# Build the backup command line and associated filenames.
+# Parameters -none.
+# No return value.
+build_bckupCL()
+{
+	local msg
+	local snarpath
+
+	bckupCL="tar -cpz --format=posix -f "
+
+
+	case $bckuptype in
+	differential)
+		# Build the backup & incremental file names and paths
+		backpath="$mntdir/backup"$(date +%a)".tar.gz"
+		snarpath="$mntdir/backup"$(date +%a)".snar"
+
+		# If the incremental files exists, delete.
+		# (Just in case full backup has not done this)
+		if [[ -f $snarpath ]]; then
+			rm "$snarpath"
+			std_cmd_err_handler $?
+		fi
+
+		# Copy level 0 incremental file in order to perform a
+		# level 1, effective differential backup each run.
+		if [[ -f $mntdir/backup.snar && -r $mntdir/backup.snar \
+			&& -w $mntdir/backup.snar ]]; then
+			cp "$mntdir/backup.snar" "$snarpath"
+			std_cmd_err_handler $?
+		else
+			status=66
+			msg="backup.snar does not exist or is not accessible. "
+			msg+="Exit code $status"
+			output "$msg" 1 1
+			script_exit $status
+		fi
+
+		bckupCL+="$backpath "
+		bckup_CL+="--exclude-from=$etclocation/bckdaily.exclude "
+		# Exclude system and cache directories
+		bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
+		bckupCL+="--exclude-from=$tmpexclfile "
+		bckupCL+="--exclude-caches "
+		bckupCL+="--listed-incremental=$snarpath "
+		;;
+	fulladhoc)
+		# Build the backup file name and path
+		backpath="$mntdir/backup$(date '+%Y%m%d%H%M').tar.gz"
+
+		bckupCL+="$backpath "
+		# Exclude system and cache directories
+		bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
+		bckupCL+="--exclude-from=$tmpexclfile "
+		bckupCL+="--exclude-caches "
+		;;
+	incremental)
+		# Build the backup & incremental file names and paths
+		backpath="$mntdir/backup$(date +%a).tar.gz"
+		snarpath="$mntdir/backup.snar"
+
+		# Check that the incremental file exists.
+		if [[ ! -f $snarpath || ! -r $snarpath \
+			|| ! -w $snarpath ]]; then
+			status=66
+			msg="$snarpath does not exist or is not accessible. "
+			msg+="Exit code $status"
+			output "$msg" 1 1
+			script_exit $status
+		fi
+
+		bckupCL+="$backpath "
+		bckupCL+="--exclude-from=$etclocation/bckdaily.exclude "
+		# Exclude system and cache directories
+		bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
+		bckupCL+="--exclude-from=$tmpexclfile "
+		bckupCL+="--exclude-caches "
+		bckupCL+="--listed-incremental=$snarpath "
+		;;
+	selective)
+		# Build the backup file name and path
+		backpath="$mntdir/backupsel$(date +%a).tar.gz"
+
+		bckupCL+="$backpath "
+		bckupCL+="--exclude-from=$etclocation/bckseldaily.exclude "
+		# Exclude system and cache directories
+		bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
+		bckupCL+="--exclude-from=$tmpexclfile "
+		bckupCL+="--exclude-caches "
+		bckupCL+="--files-from=$etclocation/bckseldaily.files "
+		;;
+	weekly)
+		# Build the backup & incremental file names and paths
+		backpath="$mntdir/backup$bckseq.tar.gz"
+		snarpath="$mntdir/backup.snar"
+
+		# If the level 0 incremental file exists, delete
+		if [[ -f $snarpath ]]; then
+			rm "$snarpath"
+			std_cmd_err_handler $?
+		fi
+
+		bckupCL+="$backpath "
+		bckupCL+="--exclude-from=$etclocation/bckweekly.exclude "
+		# Exclude system and cache directories
+		bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
+		bckupCL+="--exclude-from=$tmpexclfile "
+		bckupCL+="--exclude-caches "
+		bckupCL+="--listed-incremental=$snarpath "
+		;;
+	esac
+}
+
 
 ########
 # Main #
@@ -629,105 +742,7 @@ std_cmd_err_handler $?
 
 prod_adhoc_excl_list
 
-# Start build of backup command
-bckupCL="tar -cpz --format=posix -f "
-
-
-case $bckuptype in
-differential)
-	# Build the backup & incremental file names and paths
-	backpath="$mntdir/backup"$(date +%a)".tar.gz"
-	snarpath="$mntdir/backup"$(date +%a)".snar"
-
-	# If the incremental files exists, delete.
-	# (Just in case full backup has not done this)
-	if [[ -f $snarpath ]]; then
-		rm "$snarpath"
-		std_cmd_err_handler $?
-	fi
-
-	# Copy level 0 incremental file in order to perform a
-	# level 1, effective differential backup each run.
-	if [[ -f $mntdir/backup.snar && -r $mntdir/backup.snar \
-		&& -w $mntdir/backup.snar ]]; then
-		cp "$mntdir/backup.snar" "$snarpath"
-		std_cmd_err_handler $?
-	else
-		status=66
-		msg="backup.snar does not exist or is not accessible. Exit "
-		msg+="code $status"
-		output "$msg" 1 1
-		script_exit $status
-	fi
-
-	bckupCL+="$backpath --exclude-from=$etclocation/bckdaily.exclude "
-	# Exclude system and cache directories
-	bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
-	bckupCL+="--exclude-from=$tmpexclfile "
-	bckupCL+="--exclude-caches "
-	bckupCL+="--listed-incremental=$snarpath "
-	;;
-fulladhoc)
-	# Build the backup file name and path
-	backpath="$mntdir/backup$(date '+%Y%m%d%H%M').tar.gz"
-
-	bckupCL+="$backpath "
-	# Exclude system and cache directories
-	bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
-	bckupCL+="--exclude-from=$tmpexclfile "
-	bckupCL+="--exclude-caches "
-	;;
-incremental)
-	# Build the backup & incremental file names and paths
-	backpath="$mntdir/backup$(date +%a).tar.gz"
-	snarpath="$mntdir/backup.snar"
-
-	# Check that the incremental file exists.
-	if [[ ! -f $snarpath || ! -r $snarpath || ! -w $snarpath ]]; then
-		status=66
-		msg="$snarpath does not exist or is not accessible. Exit "
-		msg+="code $status"
-		output "$msg" 1 1
-		script_exit $status
-	fi
-
-	bckupCL+="$backpath --exclude-from=$etclocation/bckdaily.exclude "
-	# Exclude system and cache directories
-	bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
-	bckupCL+="--exclude-from=$tmpexclfile "
-	bckupCL+="--exclude-caches "
-	bckupCL+="--listed-incremental=$snarpath "
-	;;
-selective)
-	# Build the backup file name and path
-	backpath="$mntdir/backupsel$(date +%a).tar.gz"
-
-	bckupCL+="$backpath --exclude-from=$etclocation/bckseldaily.exclude "
-	# Exclude system and cache directories
-	bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
-	bckupCL+="--exclude-from=$tmpexclfile "
-	bckupCL+="--exclude-caches "
-	bckupCL+="--files-from=$etclocation/bckseldaily.files "
-	;;
-weekly)
-	# Build the backup & incremental file names and paths
-	backpath="$mntdir/backup$bckseq.tar.gz"
-	snarpath="$mntdir/backup.snar"
-
-	# If the level 0 incremental file exists, delete
-	if [[ -f $snarpath ]]; then
-		rm "$snarpath"
-		std_cmd_err_handler $?
-	fi
-
-	bckupCL+="$backpath --exclude-from=$etclocation/bckweekly.exclude "
-	# Exclude system and cache directories
-	bckupCL+="--exclude-from=$etclocation/bcksystem.exclude "
-	bckupCL+="--exclude-from=$tmpexclfile "
-	bckupCL+="--exclude-caches "
-	bckupCL+="--listed-incremental=$snarpath "
-	;;
-esac
+build_bckupCL
 
 # If the backup file exists, delete
 if [[ -f $backpath ]]; then
