First release of chkbckshare. v1.1.1 as major revamp to all IXBackups scripts.

diff --git a/scripts/detbckshare b/scripts/detbckshare
--- a/scripts/detbckshare
+++ b/scripts/detbckshare
@@ -66,6 +66,9 @@
 ##				require a name change, or, if left	##
 ##				as-is would cause confusion. So name	##
 ##				changed to remove .sh extension.	##
+## 18/12/2013	MG	1.0.10	Changed stdout & stderr message output	##
+##				to use a function directing to one or	##
+##				other based on a status.		##
 ##									##
 ##########################################################################
 
@@ -73,23 +76,29 @@
 ## Init variables ##
 ####################
 script_exit_code=0
-version="1.0.9"				# set version variable
+version="1.0.10"			# set version variable
 etclocation=/usr/local/etc/backups	# Path to etc directory
 
 ###############
 ## Functions ##
 ###############
-# Standard function to log $1 to stderr
-mess_log()
+
+# Output $1 to stdout or stderr depending on $2
+output()
 {
-echo $1 1>&2
+	if [ $2 = 0 ]
+	then
+		echo "detbckshare: $1"
+	else
+		echo "detbckshare: $1" 1>&2
+	fi
 }
 
-# Standard function to message stderr, any cleanup and return exit code
+# Standard function to announce $1 and return exit code
 script_exit()
 {
-mess_log "$1" 
-exit $script_exit_code
+	output $1 $script_exit_code
+	exit $script_exit_code
 }
 
 # Standard trap exit function
@@ -116,8 +125,8 @@ do
 			;;
 		v)	echo "$0 version "$version
 			;;
-		\?)	echo "Invalid argument -$OPTARG." >&2
-			exit 64
+		\?)	script_exit_code=64
+			script_exit "Invalid argument -$OPTARG."
 			;;
 	esac
 done
@@ -156,4 +165,5 @@ if [ "$(mount | grep "/mnt/$bckupdir")" != "" ]
 	script_exit_code=66
 	script_exit "Backup share not mounted. Script exit code: "$script_exit_code
 fi
-exit 0
+script_exit_code=0
+script_exit "Share unmounted from /mnt/$bckupdir"
