Changes for v1.1.1 release finalised for chkbckshare and bckdatadaily.

diff --git a/scripts/scriptssrc/bckdatadaily.in b/scripts/scriptssrc/bckdatadaily.in
--- a/scripts/scriptssrc/bckdatadaily.in
+++ b/scripts/scriptssrc/bckdatadaily.in
@@ -15,7 +15,7 @@
 ## Backs up directories and files specified in backup.files file.	##
 ## The timing element is expected to be delivered via cron.		##
 ##									##
-## Syntax:	bckincdaily [-h || --help || -v || --version]		##
+## Syntax:	bckincdaily [-h || -v]					##
 ##									##
 ## Exit Codes:	0 & 64 - 113 as per C/C++ standard			##
 ##		0 - success						##
@@ -51,40 +51,66 @@
 ##				of the tar command as this adds the	##
 ##				root directory as a backup start point	##
 ##				in addition to --files-from.		##
+## 22/12/2013	MG	1.1.1	Changed stdout & stderr message output	##
+##				to use a function directing to one or	##
+##				other based on a status.		##
 ##									##
 ##########################################################################
 
-exec 6>&1 7>&2 # Immediately make copies of stdout & stderr
+exec 6>&1 7>&2	# Immediately make copies of stdout & stderr
 
 ####################
 ## Init variables ##
 ####################
 script_exit_code=0
-version="1.0.4"				# set version variable
+version="1.1.1"				# set version variable
 etclocation=@sysconfdir@/backups	# Path to etc directory
+outputprefix="bckdatadaily: "
 
 # Get system name for implementing OS differences
 osname=$(uname -s)
 
+# Form mail message subject line
+script_short_desc=$(uname -n)" "$(date +%A)" Daily Data Backup"
+
 ###############
 ## Functions ##
 ###############
-script_short_desc=$(uname -n)" "$(date +%A)" Daily Data Backup"
 
-# Standard function to log $1 to stderr and mail to recipient
-mess_log()
+# Output $1 to stdout or stderr depending on $2 and mail to recipient
+output()
 {
-echo $1 1>&2
-echo $1 | mailx -s "$script_short_desc" $mail_recipient
+	if [ $2 = 0 ]
+	then
+		echo "$outputprefix$1"
+	else
+		echo "$outputprefix$1" 1>&2
+	fi
+	echo $1 | mailx -s "$script_short_desc" $mail_recipient
 }
 
-# Standard function to log and mail $1, cleanup and return exit code
+# Standard function to cleanup and return exit code
 script_exit()
 {
-mess_log "$1" 
-exec 1>&6 2>&7 6>&- 7>&- # Restore stdin & stdout & close fd's 6 & 7
+# FD's 6 & 7 may or may not be open at this point so test individually for closing.
+# This reads lsof with ANDed conditions of suppress warnings, FD 6, output only FD
+# for this current PID and pipe it's output to wc to count the lines. If FD 6 is
+# open, 2 lines result, PID number and f6.
+if [ $(lsof -aw -d 6 -F f -p $$ | wc -l) -gt 0 ]
+then
+	exec 1>&6 6>&-	# Restore stdout and close FD 6
+fi
+if [ $(lsof -aw -d 7 -F f -p $$ | wc -l) -gt 0 ]
+then
+	exec 2>&7 7>&-	# Restore stderr and close FD 7
+fi
+
 sleep 5
-detbckshare
+if [ "$(chkbckshare -bt)" = "TRUE" ]
+then
+	detbckshare
+fi
+
 exit $script_exit_code
 }
 
@@ -92,7 +118,8 @@ exit $script_exit_code
 trap_exit()
 {
 script_exit_code=67
-script_exit "Script terminating due to trap received. Code: "$script_exit_code
+output "Script terminating due to trap received." 1
+script_exit
 }
 
 # Setup trap
@@ -105,23 +132,29 @@ trap trap_exit SIGHUP SIGINT SIGTERM
 while getopts :hv arg
 do
 	case $arg in
-		h)	echo "Usage is $0 [options]"
-			echo "	-h displays usage information"
-			echo "	OR"
-			echo "	-v displays version information"
-			;;
-		v)	echo "$0 version "$version
-			;;
-		\?)	echo "Invalid argument -$OPTARG." >&2
-			exit 64
-			;;
+	h)	echo "Usage is $0 [options]"
+		echo "	-h displays usage information"
+		echo "	OR"
+		echo "	-v displays version information"
+		script_exit_code=0
+		script_exit
+		;;
+	v)	echo "$0 version "$version
+		script_exit_code=0
+		script_exit
+		;;
+	\?)	script_exit_code=64
+		output "Invalid argument -$OPTARG." 1
+		script_exit
+		;;
 	esac
 done
 
 # If help or version requested then exit now.
 if [ $# -gt 0 ]
 	then
-		exit 0
+		script_exit_code=0
+		script_exit
 fi
 
 # Read parameters from $etclocation/backups.conf
@@ -150,13 +183,15 @@ status=$?
 if [ $status != "0" -a $status != "66" ]
 	then
 	script_exit_code=65
-	script_exit "Failed to mount backup NAS server. Mount error: "$status" Script exit code: "$script_exit_code
+	output "Failed to mount backup NAS server. Mount error: "$status 1
+	script_exit
 fi
 
 # Re-direct stdout & stderr to backup logs and write initial entries
 exec 1>> /mnt/$bckupdir/backup.log 2>> /mnt/$bckupdir/backuperror.log
-echo "Attempting to process backup - "$backpath
-mess_log "Attempting to process backup - "$backpath
+
+output "Attempting to process backup - "$backpath 0
+echo "Attempting to process backup - "$backpath 1>&2
 
 date
 date 1>&2
@@ -197,8 +232,9 @@ esac
 # Final log entries and restore stdout & stderr
 date
 date 1>&2
-echo "Processing of "$backpath" is complete. Status: "$status
-mess_log "Processing of "$backpath" is complete. Status: "$status
+output "Processing of "$backpath" is complete. Status: "$status 0
+echo "Processing of "$backpath" is complete. Status: "$status 1>&2
+
 ##################################################################
 ## It is not clear why the following two lines cause everything ##
 ## to hang until charybdis is restarted. It is probably due to  ##
@@ -235,8 +271,7 @@ sleep 5
 mv /mnt/$bckupdir/tmp.log /mnt/$bckupdir/backuperror.log
 sleep 5
 
-# Unmount the backup NAS server
-detbckshare
-
 # And exit
-exit 0
+script_exit_code=0
+output "Daily Data Backup Complete." 0
+script_exit
