Changed to use -V as version option. Introduced standard error handling function. introduced --interactive=never option for rm commands.

diff --git a/scripts/scriptssrc/bckincdaily.in b/scripts/scriptssrc/bckincdaily.in
--- a/scripts/scriptssrc/bckincdaily.in
+++ b/scripts/scriptssrc/bckincdaily.in
@@ -19,7 +19,7 @@
 ## for daily coverage, designated by the short day form. The		##
 ## timing element is expected to be delivered via cron.			##
 ##									##
-## Syntax:	bckincdaily [-h || --help || -v || --version]		##
+## Syntax:	bckincdaily [-h || -V ]					##
 ##									##
 ## Exit Codes:	0 & 64 - 113 as per C/C++ standard			##
 ##		0 - success						##
@@ -94,9 +94,12 @@
 ## 30/10/2013	MG	1.0.21	Removed '-' prepending operations in	##
 ##				the tar command. Added --exclude-caches	##
 ##				to the tar command.			##
-## 28/12/2013	MG	1.1.1	Changed stdout & stderr message output	##
+## 07/01/2014	MG	1.1.1	Changed stdout & stderr message output	##
 ##				to use a function directing to one or	##
-##				other based on a status.		##
+##				other based on a status. Changed	##
+##				version option to -V. Added usage of	##
+##				standard error routine. Added		##
+##				interactive=never to rm commands.	##
 ##									##
 ##########################################################################
 
@@ -131,6 +134,16 @@ output()
 	if [ "$mail_recipient" != "" ]
 	then
 		echo $1 | mailx -s "$script_short_desc" $mail_recipient
+	fi
+}
+
+# Standard function to test command error ($1 is $?) and exit if non-zero
+std_cmd_err_handler()
+{
+	if [ $1 != 0 ]
+	then
+		script_exit_code=$1
+		script_exit
 	fi
 }
 
@@ -174,17 +187,17 @@ trap trap_exit SIGHUP SIGINT SIGTERM
 ## Main ##
 ##########
 # Process command line arguments with getopts.
-while getopts :hv arg
+while getopts :hV arg
 do
 	case $arg in
 	h)	echo "Usage is $0 [options]"
 		echo "	-h displays usage information"
 		echo "	OR"
-		echo "	-v displays version information"
+		echo "	-V displays version information"
 		script_exit_code=0
 		script_exit
 		;;
-	v)	echo "$0 version "$version
+	V)	echo "$0 version "$version
 		script_exit_code=0
 		script_exit
 		;;
@@ -217,13 +230,10 @@ backpath="/mnt/$bckupdir/backup"$(date +%a)".tar.gz"
 snarpath="/mnt/$bckupdir/backup"$(date +%a)".snar"
 
 # Check to see if the NAS backup server is mounted, if not, mount
-attbckshare
-status=$?
-if [ $status != "0" -a $status != "66" ]
+if [ "$(chkbckshare -bt)" = "FALSE" ]
 then
-	script_exit_code=65
-	output "Failed to mount backup NAS server. Mount error: "$status 1
-	script_exit
+	attbckshare
+	std_cmd_err_handler $?
 fi
 
 # Re-direct stdout & stderr to backup logs and write initial entries
@@ -237,18 +247,21 @@ date 1>&2
 
 # If the backup or incremental files exists, delete.
 # (Just in case full backup has not done this)
-if [ -f $backpath -a -r $backpath -a -w $backpath ]
+if [ -f $backpath ]
 then
-	rm $backpath
+	rm --interactive=never $backpath
+	std_cmd_err_handler $?
 fi
 
-if [ -f $snarpath -a -r $snarpath -a -w $snarpath ]
+if [ -f $snarpath ]
 then
-	rm $snarpath
+	rm --interactive=never $snarpath
+	std_cmd_err_handler $?
 fi
 
 # Empty the NAS trashbox
-rm /mnt/$bckupdir/trashbox/*
+rm --interactive=never -r /mnt/$bckupdir/trashbox/*
+std_cmd_err_handler $?
 
 # Copy level 0 incremental file in order to perform a
 # level 1, effective differential backup each run.
@@ -256,6 +269,7 @@ if [ -f /mnt/$bckupdir/backup.snar -a -r /mnt/$bckupdir/backup.snar \
 	-a -w /mnt/$bckupdir/backup.snar ]
 then
 	cp /mnt/$bckupdir/backup.snar $snarpath
+	std_cmd_err_handler $?
 else
 	script_exit_code=66
 	output "backup.snar does not exist or is not accessible. Exit code "$script_exit_code 1
@@ -315,16 +329,22 @@ exec 1>&6 2>&7 6>&- 7>&- # Restore stdout & stderr & close fd's 6 & 7
 
 # Cleanup logs so they only have 1000 lines max
 tail -n 1000 /mnt/$bckupdir/backup.log > /mnt/$bckupdir/tmp.log
+std_cmd_err_handler $?
 sleep 5
-rm /mnt/$bckupdir/backup.log
+rm --interactive=never /mnt/$bckupdir/backup.log
+std_cmd_err_handler $?
 sleep 5
 mv /mnt/$bckupdir/tmp.log /mnt/$bckupdir/backup.log
+std_cmd_err_handler $?
 sleep 5
 tail -n 1000 /mnt/$bckupdir/backuperror.log > /mnt/$bckupdir/tmp.log
+std_cmd_err_handler $?
 sleep 5
-rm /mnt/$bckupdir/backuperror.log
+rm --interactive=never /mnt/$bckupdir/backuperror.log
+std_cmd_err_handler $?
 sleep 5
 mv /mnt/$bckupdir/tmp.log /mnt/$bckupdir/backuperror.log
+std_cmd_err_handler $?
 sleep 5
 
 # And exit
