setup.sh. Now at v1.0.7. Changed stdout & stderr message output to use a function directing to one or other based on a status.

diff --git a/scripts/scriptssrc/setup.sh.in b/scripts/scriptssrc/setup.sh.in
--- a/scripts/scriptssrc/setup.sh.in
+++ b/scripts/scriptssrc/setup.sh.in
@@ -93,6 +93,9 @@
 ##				directory under sysconfdir. Added	##
 ##				exclude files for system, weekly, daily	##
 ##				and data.				##
+## 18/12/2013	MG	1.0.7	Changed stdout & stderr message output	##
+##				to use a function directing to one or	##
+##				other based on a status.		##
 ##									##
 ##########################################################################
 
@@ -101,23 +104,29 @@
 ####################
 script_exit_code=0
 osname=$(uname -s)			# Get system name for OS differentiation
-version="1.0.6"				# set version variable
+version="1.0.7"				# set version variable
 etclocation=@sysconfdir@/backups	# Path to etc directory
 
 ###############
 ## Functions ##
 ###############
-# Standard function to log $1 to stderr
-mess_log()
+
+# Output $1 to stdout or stderr depending on $2
+output()
 {
-echo $1 1>&2
+	if [ $2 = 0 ]
+	then
+		echo "setup.sh: $1"
+	else
+		echo "setup.sh: $1" 1>&2
+	fi
 }
 
-# Standard function to message stderr, any cleanup and return exit code
+# Standard function to announce $1 and return exit code
 script_exit()
 {
-mess_log "$1" 
-exit $script_exit_code
+	output $1 $script_exit_code
+	exit $script_exit_code
 }
 
 # Standard trap exit function
@@ -144,8 +153,8 @@ do
 			;;
 		v)	echo "$0 version "$version
 			;;
-		\?)	echo "Invalid argument -$OPTARG." >&2
-			exit 64
+		\?)	script_exit_code=64
+			script_exit "Invalid argument -$OPTARG."
 			;;
 	esac
 done
@@ -157,8 +166,8 @@ if [ $# -gt 0 ]
 fi
 
 if test -f ~/.nsmbrc || test -f $etclocation/backups.conf ; then
-	echo "File(s) exist, they must be maintained with an editor."
-	exit 65
+	script_exit_code=65
+	script_exit "File(s) exist, they must be maintained with an editor."
 fi
 
 read -p "NAS server name: " bckupsys
@@ -202,4 +211,5 @@ touch $etclocation/bckincdaily.exclude
 touch $etclocation/bckdatadaily.files
 touch $etclocation/bckdatadaily.exclude
 
-exit 0
+script_exit_code=0
+script_exit "Files set up."
